# Generated by Django 5.1.5 on 2025-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Circle', models.CharField(max_length=100)),
                ('Old_site_id', models.CharField(max_length=100)),
                ('New_Site_Id', models.CharField(max_length=100)),
                ('Integration_Date', models.DateField()),
                ('MS1_Date', models.DateField()),
                ('Old_site_technology', models.CharField(max_length=100)),
                ('Allocated_technology', models.CharField(max_length=100)),
                ('Deployed_technology_Deviation', models.CharField(max_length=100)),
                ('No_of_deviated_tech', models.CharField(max_length=100)),
                ('Old_site_locked_date', models.DateField()),
                ('New_site_unlock_date', models.DateField()),
                ('Old_site_traffic', models.CharField(max_length=100)),
                ('Existing_traffic', models.CharField(max_length=100)),
                ('Old_site_admin_status', models.CharField(max_length=100)),
                ('New_site_admin_status', models.CharField(max_length=100)),
                ('Both_site_unlocked', models.CharField(max_length=100)),
                ('Both_site_locked', models.CharField(max_length=100)),
                ('Pre_less_then_3_Mbps', models.CharField(max_length=100)),
                ('Current_less_then_3_Mbps', models.CharField(max_length=100)),
            ],
        ),
    ]
